#### general settings
name: LOLv2_real_model
use_tb_logger: true
model: Base_model_Impl
distortion: sr
scale: 1
gpu_ids: [ 0 ]

#### datasets
datasets:
  train:
    name: indoor
    mode: video_samesize_lol2
    interval_list: [ 1 ]
    random_reverse: false
    border_mode: false
    dataroot_GT: LOL-v2/Real_captured/Train/Normal
    dataroot_LQ: LOL-v2/Real_captured/Train/Low
    train_size: [ 600, 400 ]
    cache_keys: ~
    cache_data: true
    padding: new_info

    N_frames: 5     # how many frames as a input.
    use_shuffle: true
    n_workers: 2  # per GPU
    batch_size: 12
    GT_size: 128     # size you want to crop out as input sample.
    LQ_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: REDS4
    mode: video_samesize_lol2
    dataroot_GT: LOL-v2/Real_captured/Test/Normal
    dataroot_LQ: LOL-v2/Real_captured/Test/Low
    cache_data: true
    N_frames: 5
    padding: new_info
    train_size: [ 600, 400 ]

#### network structures
network_G:
  which_model_G: gl_former
  nf: 64
  nframes: 5      # must be same as N_frames in dataset.
  groups: 8
  front_RBs: 1
  back_RBs: 1
  predeblur: true     # default false
  HR_in: true       # true if size(input) == size(HR)
  w_TSA: true
  window_count: 4

#### path
path:
  root: ./
  strict_load: false
  vgg19_path: vgg19-dcbb9e9d.pth
  # resume_state: path

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  beta1: 0.9
  beta2: 0.99
  niter: 100000 #600000
  ft_tsa_only: 0
  warmup_iter: -1  # -1: no warm up

  # MultiStepLR的配置参数
  lr_scheme: MultiStepLR
  lr_steps: [100000 ] # [ 50000, 100000, 200000, 300000 ]
  lr_gamma: 0.5

  # CosineAnnealingLR的配置参数
  T_max: 20000
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  vgg_weight: 0.1
  contrast_weight: 0.01

  clear_step: 10
  adj_table_maxsize: 300
  adj_table_item_maxsize: 10
  adj_history_negative_ratio: 1
  adj_negative_count: 4
  adj_save_ratio: 0.5
  adj_clear_key_ratio: 0.1

  val_freq: 30
  is_save_val_img: false
  is_val_ssim: false
  manual.resize960x512_seed: 0

#### logger
logger:
  print_freq: 30
  save_checkpoint_psnr_th: 20.0 # 保存模型的psnr阈值
